[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "horgues3"
version = "0.1.0"

[tool.setuptools.packages.find]
include = ["horgues3*"]